// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/fountain.dart';
import 'api/qr.dart';
import 'api/simple.dart';
import 'api/vcode.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 227308565;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_beyond_qr',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  bool crateApiFountainFountainDecoderAddPacket({
    required FountainDecoder that,
    required List<int> packet,
  });

  FountainDecoder crateApiFountainFountainDecoderNew({
    required List<int> otiBytes,
  });

  int crateApiFountainFountainDecoderPacketsReceived({
    required FountainDecoder that,
  });

  Uint8List? crateApiFountainFountainDecoderPayload({
    required FountainDecoder that,
  });

  BigInt crateApiFountainFountainDecoderPayloadSize({
    required FountainDecoder that,
  });

  FountainEncoder crateApiFountainFountainEncoderNew({
    required List<int> payload,
    required int packetSize,
    required int extraRepair,
  });

  Uint8List crateApiFountainFountainEncoderOtiBytes({
    required FountainEncoder that,
  });

  Uint8List crateApiFountainFountainEncoderPacket({
    required FountainEncoder that,
    required int i,
  });

  int crateApiFountainFountainEncoderPacketCount({
    required FountainEncoder that,
  });

  int crateApiVcodeVcodeTxFrameCount({required VcodeTx that});

  VcodeFrameImage crateApiVcodeVcodeTxFrameGray({
    required VcodeTx that,
    required int i,
  });

  VcodeTx crateApiVcodeVcodeTxNew({
    required List<int> payload,
    required int extraRepair,
  });

  int crateApiVcodeVcodeTxPacketCount({required VcodeTx that});

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  QrMatrix crateApiQrMakeQr({
    required List<int> data,
    required String ec,
    required int minVersion,
  });

  Future<VcodeScanReport> crateApiVcodeVcodeScanGray({
    required List<int> y,
    required int width,
    required int height,
    required int stride,
    required int rotationDeg,
    required double guideFrac,
    required bool debugDump,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_FountainDecoder;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_FountainDecoder;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FountainDecoderPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_FountainEncoder;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_FountainEncoder;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FountainEncoderPtr;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_VcodeTx;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_VcodeTx;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_VcodeTxPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  bool crateApiFountainFountainDecoderAddPacket({
    required FountainDecoder that,
    required List<int> packet,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(packet, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFountainFountainDecoderAddPacketConstMeta,
        argValues: [that, packet],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFountainFountainDecoderAddPacketConstMeta =>
      const TaskConstMeta(
        debugName: "FountainDecoder_add_packet",
        argNames: ["that", "packet"],
      );

  @override
  FountainDecoder crateApiFountainFountainDecoderNew({
    required List<int> otiBytes,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(otiBytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFountainFountainDecoderNewConstMeta,
        argValues: [otiBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFountainFountainDecoderNewConstMeta =>
      const TaskConstMeta(
        debugName: "FountainDecoder_new",
        argNames: ["otiBytes"],
      );

  @override
  int crateApiFountainFountainDecoderPacketsReceived({
    required FountainDecoder that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFountainFountainDecoderPacketsReceivedConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFountainFountainDecoderPacketsReceivedConstMeta =>
      const TaskConstMeta(
        debugName: "FountainDecoder_packets_received",
        argNames: ["that"],
      );

  @override
  Uint8List? crateApiFountainFountainDecoderPayload({
    required FountainDecoder that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFountainFountainDecoderPayloadConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFountainFountainDecoderPayloadConstMeta =>
      const TaskConstMeta(
        debugName: "FountainDecoder_payload",
        argNames: ["that"],
      );

  @override
  BigInt crateApiFountainFountainDecoderPayloadSize({
    required FountainDecoder that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFountainFountainDecoderPayloadSizeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFountainFountainDecoderPayloadSizeConstMeta =>
      const TaskConstMeta(
        debugName: "FountainDecoder_payload_size",
        argNames: ["that"],
      );

  @override
  FountainEncoder crateApiFountainFountainEncoderNew({
    required List<int> payload,
    required int packetSize,
    required int extraRepair,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(payload, serializer);
          sse_encode_u_16(packetSize, serializer);
          sse_encode_u_32(extraRepair, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainEncoder,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFountainFountainEncoderNewConstMeta,
        argValues: [payload, packetSize, extraRepair],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFountainFountainEncoderNewConstMeta =>
      const TaskConstMeta(
        debugName: "FountainEncoder_new",
        argNames: ["payload", "packetSize", "extraRepair"],
      );

  @override
  Uint8List crateApiFountainFountainEncoderOtiBytes({
    required FountainEncoder that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainEncoder(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFountainFountainEncoderOtiBytesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFountainFountainEncoderOtiBytesConstMeta =>
      const TaskConstMeta(
        debugName: "FountainEncoder_oti_bytes",
        argNames: ["that"],
      );

  @override
  Uint8List crateApiFountainFountainEncoderPacket({
    required FountainEncoder that,
    required int i,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainEncoder(
            that,
            serializer,
          );
          sse_encode_u_32(i, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFountainFountainEncoderPacketConstMeta,
        argValues: [that, i],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFountainFountainEncoderPacketConstMeta =>
      const TaskConstMeta(
        debugName: "FountainEncoder_packet",
        argNames: ["that", "i"],
      );

  @override
  int crateApiFountainFountainEncoderPacketCount({
    required FountainEncoder that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainEncoder(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFountainFountainEncoderPacketCountConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFountainFountainEncoderPacketCountConstMeta =>
      const TaskConstMeta(
        debugName: "FountainEncoder_packet_count",
        argNames: ["that"],
      );

  @override
  int crateApiVcodeVcodeTxFrameCount({required VcodeTx that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeTx(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVcodeVcodeTxFrameCountConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVcodeVcodeTxFrameCountConstMeta =>
      const TaskConstMeta(debugName: "VcodeTx_frame_count", argNames: ["that"]);

  @override
  VcodeFrameImage crateApiVcodeVcodeTxFrameGray({
    required VcodeTx that,
    required int i,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeTx(
            that,
            serializer,
          );
          sse_encode_u_32(i, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vcode_frame_image,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVcodeVcodeTxFrameGrayConstMeta,
        argValues: [that, i],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVcodeVcodeTxFrameGrayConstMeta =>
      const TaskConstMeta(
        debugName: "VcodeTx_frame_gray",
        argNames: ["that", "i"],
      );

  @override
  VcodeTx crateApiVcodeVcodeTxNew({
    required List<int> payload,
    required int extraRepair,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(payload, serializer);
          sse_encode_u_32(extraRepair, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeTx,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVcodeVcodeTxNewConstMeta,
        argValues: [payload, extraRepair],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVcodeVcodeTxNewConstMeta => const TaskConstMeta(
    debugName: "VcodeTx_new",
    argNames: ["payload", "extraRepair"],
  );

  @override
  int crateApiVcodeVcodeTxPacketCount({required VcodeTx that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeTx(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVcodeVcodeTxPacketCountConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVcodeVcodeTxPacketCountConstMeta =>
      const TaskConstMeta(
        debugName: "VcodeTx_packet_count",
        argNames: ["that"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  QrMatrix crateApiQrMakeQr({
    required List<int> data,
    required String ec,
    required int minVersion,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          sse_encode_String(ec, serializer);
          sse_encode_u_8(minVersion, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_qr_matrix,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiQrMakeQrConstMeta,
        argValues: [data, ec, minVersion],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQrMakeQrConstMeta => const TaskConstMeta(
    debugName: "make_qr",
    argNames: ["data", "ec", "minVersion"],
  );

  @override
  Future<VcodeScanReport> crateApiVcodeVcodeScanGray({
    required List<int> y,
    required int width,
    required int height,
    required int stride,
    required int rotationDeg,
    required double guideFrac,
    required bool debugDump,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(y, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_u_32(stride, serializer);
          sse_encode_u_32(rotationDeg, serializer);
          sse_encode_f_64(guideFrac, serializer);
          sse_encode_bool(debugDump, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vcode_scan_report,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVcodeVcodeScanGrayConstMeta,
        argValues: [
          y,
          width,
          height,
          stride,
          rotationDeg,
          guideFrac,
          debugDump,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVcodeVcodeScanGrayConstMeta => const TaskConstMeta(
    debugName: "vcode_scan_gray",
    argNames: [
      "y",
      "width",
      "height",
      "stride",
      "rotationDeg",
      "guideFrac",
      "debugDump",
    ],
  );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_FountainDecoder => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_FountainDecoder => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_FountainEncoder => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainEncoder;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_FountainEncoder => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainEncoder;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_VcodeTx => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeTx;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_VcodeTx => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeTx;

  @protected
  FountainDecoder
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FountainDecoderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FountainEncoder
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainEncoder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FountainEncoderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  VcodeTx
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeTx(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VcodeTxImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FountainDecoder
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FountainDecoderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FountainDecoder
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FountainDecoderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FountainEncoder
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainEncoder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FountainEncoderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  VcodeTx
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeTx(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VcodeTxImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FountainDecoder
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FountainDecoderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FountainEncoder
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainEncoder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FountainEncoderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  VcodeTx
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeTx(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VcodeTxImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_prim_u_8_strict).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  QrMatrix dco_decode_qr_matrix(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return QrMatrix(
      size: dco_decode_u_32(arr[0]),
      modules: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  VcodeFrameImage dco_decode_vcode_frame_image(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return VcodeFrameImage(
      width: dco_decode_u_32(arr[0]),
      height: dco_decode_u_32(arr[1]),
      pixels: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  VcodeScanReport dco_decode_vcode_scan_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return VcodeScanReport(
      detected: dco_decode_bool(arr[0]),
      frameSeq: dco_decode_u_32(arr[1]),
      oti: dco_decode_list_prim_u_8_strict(arr[2]),
      packets: dco_decode_list_list_prim_u_8_strict(arr[3]),
      blocksOk: dco_decode_u_32(arr[4]),
      blocksTotal: dco_decode_u_32(arr[5]),
      error: dco_decode_opt_String(arr[6]),
      debugGray: dco_decode_opt_list_prim_u_8_strict(arr[7]),
      debugW: dco_decode_u_32(arr[8]),
      debugH: dco_decode_u_32(arr[9]),
    );
  }

  @protected
  FountainDecoder
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FountainDecoderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  FountainEncoder
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainEncoder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FountainEncoderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  VcodeTx
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeTx(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VcodeTxImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  FountainDecoder
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FountainDecoderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  FountainDecoder
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FountainDecoderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  FountainEncoder
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainEncoder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FountainEncoderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  VcodeTx
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeTx(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VcodeTxImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  FountainDecoder
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FountainDecoderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  FountainEncoder
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainEncoder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FountainEncoderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  VcodeTx
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeTx(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VcodeTxImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint8List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  QrMatrix sse_decode_qr_matrix(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_size = sse_decode_u_32(deserializer);
    var var_modules = sse_decode_list_prim_u_8_strict(deserializer);
    return QrMatrix(size: var_size, modules: var_modules);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  VcodeFrameImage sse_decode_vcode_frame_image(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_pixels = sse_decode_list_prim_u_8_strict(deserializer);
    return VcodeFrameImage(
      width: var_width,
      height: var_height,
      pixels: var_pixels,
    );
  }

  @protected
  VcodeScanReport sse_decode_vcode_scan_report(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_detected = sse_decode_bool(deserializer);
    var var_frameSeq = sse_decode_u_32(deserializer);
    var var_oti = sse_decode_list_prim_u_8_strict(deserializer);
    var var_packets = sse_decode_list_list_prim_u_8_strict(deserializer);
    var var_blocksOk = sse_decode_u_32(deserializer);
    var var_blocksTotal = sse_decode_u_32(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    var var_debugGray = sse_decode_opt_list_prim_u_8_strict(deserializer);
    var var_debugW = sse_decode_u_32(deserializer);
    var var_debugH = sse_decode_u_32(deserializer);
    return VcodeScanReport(
      detected: var_detected,
      frameSeq: var_frameSeq,
      oti: var_oti,
      packets: var_packets,
      blocksOk: var_blocksOk,
      blocksTotal: var_blocksTotal,
      error: var_error,
      debugGray: var_debugGray,
      debugW: var_debugW,
      debugH: var_debugH,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder(
    FountainDecoder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FountainDecoderImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainEncoder(
    FountainEncoder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FountainEncoderImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeTx(
    VcodeTx self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as VcodeTxImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder(
    FountainDecoder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FountainDecoderImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder(
    FountainDecoder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FountainDecoderImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainEncoder(
    FountainEncoder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FountainEncoderImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeTx(
    VcodeTx self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as VcodeTxImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainDecoder(
    FountainDecoder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FountainDecoderImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFountainEncoder(
    FountainEncoder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FountainEncoderImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVcodeTx(
    VcodeTx self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as VcodeTxImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_qr_matrix(QrMatrix self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.size, serializer);
    sse_encode_list_prim_u_8_strict(self.modules, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_vcode_frame_image(
    VcodeFrameImage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_list_prim_u_8_strict(self.pixels, serializer);
  }

  @protected
  void sse_encode_vcode_scan_report(
    VcodeScanReport self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.detected, serializer);
    sse_encode_u_32(self.frameSeq, serializer);
    sse_encode_list_prim_u_8_strict(self.oti, serializer);
    sse_encode_list_list_prim_u_8_strict(self.packets, serializer);
    sse_encode_u_32(self.blocksOk, serializer);
    sse_encode_u_32(self.blocksTotal, serializer);
    sse_encode_opt_String(self.error, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.debugGray, serializer);
    sse_encode_u_32(self.debugW, serializer);
    sse_encode_u_32(self.debugH, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class FountainDecoderImpl extends RustOpaque implements FountainDecoder {
  // Not to be used by end users
  FountainDecoderImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  FountainDecoderImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_FountainDecoder,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_FountainDecoder,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_FountainDecoderPtr,
  );

  /// パケットを 1 つ追加。復元できれば内部に payload を保存し true を返す。
  bool addPacket({required List<int> packet}) => RustLib.instance.api
      .crateApiFountainFountainDecoderAddPacket(that: this, packet: packet);

  /// これまでに投入した (採用された) パケット数。
  int packetsReceived() => RustLib.instance.api
      .crateApiFountainFountainDecoderPacketsReceived(that: this);

  /// 復元済みなら payload を返す (未復元なら None)。
  Uint8List? payload() =>
      RustLib.instance.api.crateApiFountainFountainDecoderPayload(that: this);

  /// 想定 payload サイズ (バイト)。
  BigInt payloadSize() => RustLib.instance.api
      .crateApiFountainFountainDecoderPayloadSize(that: this);
}

@sealed
class FountainEncoderImpl extends RustOpaque implements FountainEncoder {
  // Not to be used by end users
  FountainEncoderImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  FountainEncoderImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_FountainEncoder,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_FountainEncoder,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_FountainEncoderPtr,
  );

  /// 受信側に渡す 12 バイトの OTI (decoder 構築に必須)。
  Uint8List otiBytes() =>
      RustLib.instance.api.crateApiFountainFountainEncoderOtiBytes(that: this);

  /// i 番目のシリアライズ済みパケット (4 バイト ID + symbol_size バイト data)。
  Uint8List packet({required int i}) => RustLib.instance.api
      .crateApiFountainFountainEncoderPacket(that: this, i: i);

  /// 生成済みパケットの総数。送信側はこの値で循環表示する (Dart 側 int)。
  int packetCount() => RustLib.instance.api
      .crateApiFountainFountainEncoderPacketCount(that: this);
}

@sealed
class VcodeTxImpl extends RustOpaque implements VcodeTx {
  // Not to be used by end users
  VcodeTxImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  VcodeTxImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_VcodeTx,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_VcodeTx,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_VcodeTxPtr,
  );

  /// ループ 1 周のフレーム数 (= ceil(packet_count / ブロック数))
  int frameCount() =>
      RustLib.instance.api.crateApiVcodeVcodeTxFrameCount(that: this);

  /// i 番目のフレーム画像を生成する。パケットは循環割り当てなので全フレームが満杯になる。
  VcodeFrameImage frameGray({required int i}) =>
      RustLib.instance.api.crateApiVcodeVcodeTxFrameGray(that: this, i: i);

  int packetCount() =>
      RustLib.instance.api.crateApiVcodeVcodeTxPacketCount(that: this);
}
