// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FountainDecoder>>
abstract class FountainDecoder implements RustOpaqueInterface {
  /// パケットを 1 つ追加。復元できれば内部に payload を保存し true を返す。
  bool addPacket({required List<int> packet});

  /// 12 バイトの OTI から初期化する。
  factory FountainDecoder({required List<int> otiBytes}) => RustLib.instance.api
      .crateApiFountainFountainDecoderNew(otiBytes: otiBytes);

  /// これまでに投入した (採用された) パケット数。
  int packetsReceived();

  /// 復元済みなら payload を返す (未復元なら None)。
  Uint8List? payload();

  /// 想定 payload サイズ (バイト)。
  BigInt payloadSize();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FountainEncoder>>
abstract class FountainEncoder implements RustOpaqueInterface {
  /// payload を packet_size バイトで符号化。extra_repair はリペアパケットの追加数 (損失耐性)。
  factory FountainEncoder({
    required List<int> payload,
    required int packetSize,
    required int extraRepair,
  }) => RustLib.instance.api.crateApiFountainFountainEncoderNew(
    payload: payload,
    packetSize: packetSize,
    extraRepair: extraRepair,
  );

  /// 受信側に渡す 12 バイトの OTI (decoder 構築に必須)。
  Uint8List otiBytes();

  /// i 番目のシリアライズ済みパケット (4 バイト ID + symbol_size バイト data)。
  Uint8List packet({required int i});

  /// 生成済みパケットの総数。送信側はこの値で循環表示する (Dart 側 int)。
  int packetCount();
}
