// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ec_level`

/// data を QR 化してモジュール行列を返す。
/// min_version=0 なら容量に収まる最小版を自動選択、1..=40 ならその版に固定。
QrMatrix makeQr({
  required List<int> data,
  required String ec,
  required int minVersion,
}) => RustLib.instance.api.crateApiQrMakeQr(
  data: data,
  ec: ec,
  minVersion: minVersion,
);

/// QR のモジュール行列。row-major で size*size 個、1=暗 (黒), 0=明 (白)。
class QrMatrix {
  final int size;
  final Uint8List modules;

  const QrMatrix({required this.size, required this.modules});

  @override
  int get hashCode => size.hashCode ^ modules.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QrMatrix &&
          runtimeType == other.runtimeType &&
          size == other.size &&
          modules == other.modules;
}
