// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `fail`

/// カメラの Y プレーンから vcode をスキャンする。
///
/// - stride: Y プレーンの行バイト数 (>= width)
/// - rotation_deg: 反時計回りに画像を起こす回転 (0/90/180/270)。
///   Android は通常 sensorOrientation=90 のとき 90 を渡す。
/// - guide_frac: 回転後画像の幅に対するガイド枠幅の比 (UI のガイド枠と同じ値を渡す)
Future<VcodeScanReport> vcodeScanGray({
  required List<int> y,
  required int width,
  required int height,
  required int stride,
  required int rotationDeg,
  required double guideFrac,
  required bool debugDump,
}) => RustLib.instance.api.crateApiVcodeVcodeScanGray(
  y: y,
  width: width,
  height: height,
  stride: stride,
  rotationDeg: rotationDeg,
  guideFrac: guideFrac,
  debugDump: debugDump,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VcodeTx>>
abstract class VcodeTx implements RustOpaqueInterface {
  /// ループ 1 周のフレーム数 (= ceil(packet_count / ブロック数))
  int frameCount();

  /// i 番目のフレーム画像を生成する。パケットは循環割り当てなので全フレームが満杯になる。
  VcodeFrameImage frameGray({required int i});

  /// payload を vcode 用に符号化する。extra_repair はリペアパケット追加数。
  /// packet_size はレイアウトから決まる (V0 = 44 バイト)。
  factory VcodeTx({required List<int> payload, required int extraRepair}) =>
      RustLib.instance.api.crateApiVcodeVcodeTxNew(
        payload: payload,
        extraRepair: extraRepair,
      );

  int packetCount();
}

/// フレーム画像 (グレースケール、1 セル = 1 ピクセル)
class VcodeFrameImage {
  final int width;
  final int height;

  /// 0=黒, 255=白 の行優先グレースケール
  final Uint8List pixels;

  const VcodeFrameImage({
    required this.width,
    required this.height,
    required this.pixels,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ pixels.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VcodeFrameImage &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          pixels == other.pixels;
}

/// スキャン結果。detected=false のとき error に理由 (デバッグログ用)。
class VcodeScanReport {
  final bool detected;
  final int frameSeq;
  final Uint8List oti;

  /// CRC が通ったブロックのペイロード (= シリアライズ済み RaptorQ パケット) 列
  final List<Uint8List> packets;
  final int blocksOk;
  final int blocksTotal;
  final String? error;

  /// debug_dump=true のとき、回転処理後のグレースケール画像 (PC 側解析用)
  final Uint8List? debugGray;
  final int debugW;
  final int debugH;

  const VcodeScanReport({
    required this.detected,
    required this.frameSeq,
    required this.oti,
    required this.packets,
    required this.blocksOk,
    required this.blocksTotal,
    this.error,
    this.debugGray,
    required this.debugW,
    required this.debugH,
  });

  @override
  int get hashCode =>
      detected.hashCode ^
      frameSeq.hashCode ^
      oti.hashCode ^
      packets.hashCode ^
      blocksOk.hashCode ^
      blocksTotal.hashCode ^
      error.hashCode ^
      debugGray.hashCode ^
      debugW.hashCode ^
      debugH.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VcodeScanReport &&
          runtimeType == other.runtimeType &&
          detected == other.detected &&
          frameSeq == other.frameSeq &&
          oti == other.oti &&
          packets == other.packets &&
          blocksOk == other.blocksOk &&
          blocksTotal == other.blocksTotal &&
          error == other.error &&
          debugGray == other.debugGray &&
          debugW == other.debugW &&
          debugH == other.debugH;
}
