// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `fail`, `rotate_y_plane`, `success`

/// Fountain 復元結果のエンドツーエンド CRC-32 を検証して剥がす。
/// None = ブロック CRC をすり抜けたゴミパケットで復元結果が破損している
/// (受信側はデコーダを作り直して受信を続行すべき)。
Uint8List? vcodeUnwrapPayload({required List<int> payload}) =>
    RustLib.instance.api.crateApiVcodeVcodeUnwrapPayload(payload: payload);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VcodeRx>>
abstract class VcodeRx implements RustOpaqueInterface {
  factory VcodeRx() => RustLib.instance.api.crateApiVcodeVcodeRxNew();

  /// カメラの Y プレーンから vcode をスキャンする。
  /// トラッキング成功時は report.tracked = true。
  /// 注: sync にしない。非同期 (Rust ワーカースレッド実行) にすることで
  /// UI isolate をブロックせず、カメラプレビューのカクつきを防ぐ。
  Future<VcodeScanReport> scan({
    required List<int> y,
    required int width,
    required int height,
    required int stride,
    required int rotationDeg,
    required double guideFrac,
    required bool debugDump,
  });
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VcodeTx>>
abstract class VcodeTx implements RustOpaqueInterface {
  /// ループ 1 周のフレーム数 (= ceil(packet_count / ブロック数))
  int frameCount();

  /// i 番目のフレーム画像を生成する。パケットは循環割り当てなので全フレームが満杯になる。
  VcodeFrameImage frameGray({required int i});

  /// payload を vcode 用に符号化する。extra_repair はリペアパケット追加数。
  /// grid_w x grid_h はブロック格子 (5x4=標準, 7x6=高密度)。
  /// bits_per_cell: 1=白黒 (packet 42B), 2=輝度4値 (packet 92B)。
  /// payload には先頭に CRC-32 が付与される (受信側は vcode_unwrap_payload で検証して剥がす)。
  factory VcodeTx({
    required List<int> payload,
    required int extraRepair,
    required int gridW,
    required int gridH,
    required int bitsPerCell,
  }) => RustLib.instance.api.crateApiVcodeVcodeTxNew(
    payload: payload,
    extraRepair: extraRepair,
    gridW: gridW,
    gridH: gridH,
    bitsPerCell: bitsPerCell,
  );

  int packetCount();
}

/// フレーム画像 (グレースケール、1 セル = 1 ピクセル)
class VcodeFrameImage {
  final int width;
  final int height;

  /// 0=黒, 255=白 の行優先グレースケール
  final Uint8List pixels;

  const VcodeFrameImage({
    required this.width,
    required this.height,
    required this.pixels,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ pixels.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VcodeFrameImage &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          pixels == other.pixels;
}

/// スキャン結果。detected=false のとき error に理由 (デバッグログ用)。
class VcodeScanReport {
  final bool detected;

  /// トラッキング (前フレームからの追従) で検出したか (効果検証用)
  final bool tracked;
  final int frameSeq;
  final Uint8List oti;

  /// CRC が通ったブロックのペイロード (= シリアライズ済み RaptorQ パケット) 列
  final List<Uint8List> packets;
  final int blocksOk;
  final int blocksTotal;
  final String? error;

  /// debug_dump=true のとき、回転処理後のグレースケール画像 (PC 側解析用)
  final Uint8List? debugGray;
  final int debugW;
  final int debugH;

  const VcodeScanReport({
    required this.detected,
    required this.tracked,
    required this.frameSeq,
    required this.oti,
    required this.packets,
    required this.blocksOk,
    required this.blocksTotal,
    this.error,
    this.debugGray,
    required this.debugW,
    required this.debugH,
  });

  @override
  int get hashCode =>
      detected.hashCode ^
      tracked.hashCode ^
      frameSeq.hashCode ^
      oti.hashCode ^
      packets.hashCode ^
      blocksOk.hashCode ^
      blocksTotal.hashCode ^
      error.hashCode ^
      debugGray.hashCode ^
      debugW.hashCode ^
      debugH.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VcodeScanReport &&
          runtimeType == other.runtimeType &&
          detected == other.detected &&
          tracked == other.tracked &&
          frameSeq == other.frameSeq &&
          oti == other.oti &&
          packets == other.packets &&
          blocksOk == other.blocksOk &&
          blocksTotal == other.blocksTotal &&
          error == other.error &&
          debugGray == other.debugGray &&
          debugW == other.debugW &&
          debugH == other.debugH;
}
